export const ActionTypes = {
    VALIDATE_TOKEN: 'VALIDATE_TOKEN',
    GET_ORGS: 'GET_ORGS',
    GET_REPOS: 'GET_REPOS',
    GET_MEMBERS: 'GET_MEMBERS',
    GET_REPO_DETAILS: 'GET_REPO_DETAILS',
    GET_REPO_STARGAZERS: 'GET_REPO_STARGAZERS',
    USER_NAME_SET: 'USER_NAME_SET',
    LOG_OUT: 'LOG_OUT'
};
