export const ActionTypes = {
    VALIDATE_TOKEN: 'VALIDATE_TOKEN',

    GET_ORGS: 'GET_LIST_ORGS',
    GET_REPOS: 'GET_LIST_REPOS',
    GET_MEMBERS: 'GET_LIST_MEMBERS',

    GET_REPO_DETAILS: 'GET_REPO_DETAILS',
    GET_REPO_STARGAZERS: 'GET_REPO_STARGAZERS',
    USER_NAME_SET: 'USER_NAME_SET',
    LOG_OUT: 'LOG_OUT',

    SELECT_ORG: 'SELECT_ORG',

    SEARCH_ORG: 'SEARCH_ORG',
    ORG_NOT_FOUND: 'ORG_NOT_FOUND',
    ORG_FOUND: 'ORG_FOUND'
};
